In [ ]:
import numpy as np
a= np.array([[0, 1], [2, 3], [4, 5]])
a



array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
import numpy as np
b= np.array([[0, 1,2, 3], [4, 5, 6, 7]])
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
np.dot(a,b)

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [ ]:
c = np.dot(a,b)
c.max()



47